# This workflow will install Python dependencies, run tests

name: GitHub Actions Parallel Run of Inventory tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Descriptor-Application-Part-1-Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv --upgrade
          pipenv install --system
      - name: Test with pytest
        run: |
          pytest descriptor_application_part_1 -s -v --durations=0 --cov=.
  Descriptor-Application-Part-2-Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv --upgrade
          pipenv install --system
      - name: Test with pytest
        run: |
          pytest descriptor_application_part_2 -s -v --durations=0 --cov=.
  Teacher-Code-Part-1-Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv --upgrade
          pipenv install --system
      - name: Test with pytest
        run: |
          pytest teacher_code_part_1 -s -v --durations=0 --cov=.
  Teacher-Code-Part-2-Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv --upgrade
          pipenv install --system
      - name: Test with pytest
        run: |
          pytest teacher_code_part_2 -s -v --durations=0 --cov=.
  
